### ISSUE TITLE
Support table cells selection too

### ISSUE THREAD

**Issue by Eccenux** [averissimo/open-links-in-tabs#9]
Would be great if you could support table cells selection (the one you can do when holding CTRL).

You can have many links per row but in many cases I just want to open links from a single column.

Example of such table with title column selected:
![obraz](https://user-images.githubusercontent.com/1045235/125950804-3db7e6e1-8629-427d-9e72-0c485fa2e992.png)

**Comment by Eccenux** [comment]
Seems like you could use Rangy as a helper.
![obraz](https://user-images.githubusercontent.com/1045235/125956603-71e43327-c097-4251-8759-358c40785e55.png)

Table used in example:
```html
<table><tbody>
  <tr><td>a.1</td><td>a.2</td></tr>
  <tr><td>b.1</td><td>b.2</td></tr>
  <tr><td>c.1</td><td>c.2</td></tr>
</tbody></table>
```
Rough code:
```js
// get all selected nodes
// probably overkill for standard selection
function getSelectedNodes() {
    var selectedNodes = [];
    var rangySel = rangy.getSelection();
    for (var i = 0; i < rangySel.rangeCount; ++i) {
      var nodes = rangySel.getRangeAt(i).getNodes();
        selectedNodes = selectedNodes
          .concat(nodes);
    }
    return selectedNodes;
}
var rangesCount = window.getSelection().rangeCount;

// table cells are probably selected
if (rangesCount > 1) {
  var nodes = getSelectedNodes()
  console.log(nodes);
// someting is selected
} else if (rangesCount == 1) {
  console.log(rangesCount);
}
```

Rangy demo page:
https://lezuse.github.io/rangy/demos/core.html

Rangy code:
https://github.com/timdown/rangy/

**Comment by Eccenux** [comment]
Cool. That seems like it should work. Tested your \`gatherLinks\` function on my table and it worked :-)

**Comment by averissimo** [comment]
Thanks!! I'll update the official version in a few minutes
